version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=Banco_Verde

  api:
    build: .
    ports:
      # - "3001:3001"
      - "7070:7070"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/Banco_Verde

volumes:
  mongodb_data:
