version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pig_backend_users
    ports:
      - 5431:5431
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #     - rabbitmq

volumes:
  pgdata:
