version: '3'
services:
  postgres:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=blue-bank-rules
      - POSTGRES_USER=blue-bank
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: